starting_room_id = "cubicle"

# Welcome to the Story Template!
# This file explains how to create your own text adventure story using TOML.
# The game world is defined by two main things: Rooms and Choices.

# --- 1. Rooms ---
# Rooms are the locations in your world.
# Each room needs a unique ID, a description, and a list of choices.
# The `[rooms]` table holds all the rooms in your story.

# To define a room, create a section like `[rooms.new_room]`
# The name of the room must be unique.
[rooms.cubicle]
# The `description` is the text shown to the player when they enter the room.
description = "You are in a small, windowless office cubicle. Your computer screen glows softly. There's a door to the hallway to the north."
# `choices` is a list of Choice IDs available in this room.
# These IDs must match the choices you define later.
choices = [
    "look_computer",
    "open_drawer",
    "check_plant",
    "log_in_computer",
    "go_hallway",
]

[rooms.hallway]
description = "You are in a sterile-looking office hallway. The exit is to the north, and your cubicle is to the south."
choices = ["try_exit", "use_keycard", "go_cubicle"]

[rooms.outside]
description = "You've made it outside! The city air feels fresh. You are free."
choices = ["celebrate", "go_home"]


# --- 2. Choices ---
# Choices are the actions the player can take.
# Each choice needs a unique name, the text to display, and a list of actions to perform.
# The `[choices]` table holds all the choices.

# To define a choice, create a section like `[choices.look_computer]`.
# The name of the choice must be unique.
[choices.look_computer]
# `text` is what the player sees in the list of options.
text = "Look at the computer screen."
# `actions` is a list of things that happen when the player picks this choice.
# There are four types of actions:
#   - DisplayText: Shows a message to the player.
#   - GoTo: Moves the player to a new Room ID.
#   - SetFlag: Sets a boolean flag in the game state (useful for tracking progress).
#   - Quit: Ends the game.
actions = [
    { DisplayText = "The screen shows a login prompt. You'll need a password." },
]

[choices.open_drawer]
text = "Open the desk drawer."
actions = [
    { DisplayText = "You find a sticky note inside. It reads: 'password123'" },
    # This action sets the "has_password" flag to true.
    # We can use this flag to make other choices appear later.
    { SetFlag = "has_password" },
]

[choices.check_plant]
text = "Check the sad-looking office plant."
# This choice has a `condition`. It will only be shown to the player
# if the condition is met.
# `HasFlag` means the choice is only available if the player has set this flag.
condition = { HasFlag = "knows_about_keycard" }
actions = [
    { DisplayText = "Tucked into the soil, you find a plastic keycard!" },
    { SetFlag = "has_keycard" },
]

[choices.log_in_computer]
text = "Log into the computer."
condition = { HasFlag = "has_password" }
actions = [
    { DisplayText = "You log in. An email from HR says 'The keycard for the main door has been placed in the pot of the ficus plant for safekeeping.'" },
    { SetFlag = "knows_about_keycard" },
]

[choices.go_hallway]
text = "Go north to the hallway."
actions = [{ GoTo = "hallway" }]  # This moves the player to Room 1.

[choices.try_exit]
text = "Try to open the exit door."
actions = [
    { DisplayText = "It's locked. A card reader is blinking next to it." },
]

[choices.use_keycard]
text = "Use the keycard on the exit door."
condition = { HasFlag = "has_keycard" }
actions = [
    { DisplayText = "The card reader beeps and the lock clicks open." },
    { GoTo = "outside" },                                                # Move to Room 2 (Outside)
]

[choices.go_cubicle]
text = "Go south back to your cubicle."
actions = [{ GoTo = "cubicle" }]

[choices.celebrate]
text = "Celebrate your escape."
actions = [{ DisplayText = "You do a little dance. You've earned it." }]

[choices.go_home]
text = "Go home."
actions = ["Quit"] # This ends the game.
